extends: default

rules:
  trailing-spaces: disable
  indentation:
    spaces: consistent  # You can change to a specific number like 2 or 4
    indent-sequences: consistent
    level: warning      # Optional: downgrade to warning instead of error
  quoted-strings: disable
  brackets: disable
  truthy: disable
