extends: default

rules:
  line-length:
    max: 200
    level: warning

  quoted-strings:
    quote-type: any
    required: only-when-needed

  comments:
    min-spaces-from-content: 0

  comments-indentation: disable

  document-start:
    present: false

  empty-lines:
    max: 5
    max-start: 0
    max-end: 0

  key-duplicates: false

  key-ordering: false

  indentation:
    spaces: 2
    indent-sequences: false
    check-multi-line-strings: false

  truthy:
    check-keys: false
