extends: default

rules:
  trailing-spaces: disable
  indentation:
    spaces: consistent
    indent-sequences: consistent
    level: warning
  quoted-strings: disable
  brackets: disable
  truthy: disable
  line-length: disable
  document-start: disable
